---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rbcpingarch

<!-- badges: start -->
<!-- badges: end -->

The goal of rbcpingarch is to ...

## Installation

You can install the released version of rbcpingarch from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("rbcpingarch")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("luizapiancastelli/rbcpingarch")
```
-

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rbcpingarch)
library(ggplot2)
```

### Data simulation

```{r}
A = matrix(c(0.3, 0, 0, 0.1), ncol =2, byrow = TRUE)
B = matrix(c(0.2, 0, 0, 0.3), ncol =2, byrow = TRUE)
omega = c(1,1)
phi = 0.3

Y = rBCPINGARCH(A, B, omega, phi, 500)
head(Y)
cor(Y)

Y_df = data.frame('y1' =Y[,1], 'y2' = Y[,2], 't' = 1:nrow(Y))
ggplot(Y_df, aes(x = t))+
  geom_line(aes(y = y1), color = 'red') +  geom_line(aes(y = y2), color = 'blue')+theme_bw()+
  labs(y = 'Simulated count time series data', x = 'Time')

```

### Model fit

```{r, echo=FALSE}
data("Y_hep")

fit_diag = fit_BCP_INGARCH(Y_hep, A.diag = TRUE, B.diag = TRUE)
fit_diag$par
fit_diag$se
fit_diag$loglik

fit_nd = fit_BCP_INGARCH(Y_hep, A.diag = TRUE, B.diag = FALSE)
fit_nd$par
fit_nd$se
fit_nd$loglik
```

